=== blocher/dailyoffice2019/site/esv/schema/crossway.intros.dtd
<!ELEMENT crossway-intros (book)+>
<!ATTLIST crossway-intros  translation CDATA #REQUIRED
                           edition CDATA #REQUIRED
                           revision CDATA #REQUIRED>

<!ELEMENT book (p)+>
<!ATTLIST book  title CDATA #REQUIRED
                num  CDATA #REQUIRED>

<!ELEMENT p (#PCDATA|span)*>

<!ELEMENT span (#PCDATA)*>
<!ATTLIST span  class CDATA #REQUIRED>

<!ENTITY ldblquot  "&#8220;">
<!ENTITY rdblquot  "&#8221;">
<!ENTITY lquot     "&#8216;">
<!ENTITY rquot     "&#8217;">
<!ENTITY emdash    "&#8212;">
<!ENTITY endash    "&#8211;">
<!ENTITY ellipsis  "&#160;.&#160;.&#160;.">

=== blocher/dailyoffice2019/site/bible/esv/_intros.cre.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE crossway-intros SYSTEM "schema/crossway.intros.dtd">
<crossway-intros translation="English Standard Version" edition="Classic Reference Edition" revision="2025-02-02">
	<book title="Genesis" num="1">
		<p>As its name implies, Genesis is about beginnings. Genesis tells us that God created everything that exists. It shows that God is both the Creator and the Ruler of all creation. But it also tells of humanity&apos;s tragic fall into sin and death, and of God&apos;s unfolding plan of redemption through his covenant with Abraham and his descendants. Genesis includes some of the most memorable stories in the Bible, beginning with Adam and Eve (chs. 1&emdash;4), continuing through Noah, Abraham, Isaac, and Jacob, and ending with the life of Joseph (chs. 37&emdash;50), who died before 1600 <span class="chronology">BC</span>. Traditionally, Jews and Christians have recognized Moses as the author, writing after the Exodus from Egypt, commonly dated around 1440 <span class="chronology">BC</span> though some prefer a date around 1260 <span class="chronology">BC</span>.</p>
	</book>
	<book title="Exodus" num="2">
		<p>Exodus tells of God fulfilling his promise to Abraham by multiplying Abraham&apos;s descendants into a great nation, delivering them from slavery in Egypt, leading them to the Promised Land, and then binding them to himself with a covenant at Mount Sinai. Moses, under the direct command of God and as leader of Israel, received the Ten Commandments from God, along with other laws governing Israel&apos;s life and worship. He also led the nation in the building of the tabernacle, a place where God&apos;s presence dwelled among his people and where they made sacrifices for sin. Traditionally, Jews and Christians recognize Moses as the author, writing sometime after the Exodus from Egypt.</p>
	</book>
	<book title="Leviticus" num="3">
		<p>Leviticus begins with the people of Israel at the foot of Mount Sinai. The glory of the Lord had just filled the tabernacle (Ex. 40:34&endash;38) and God now tells Moses to instruct the Levitical priests and the people of Israel concerning sacrifices, worship, the priesthood, ceremonial cleanness, the Day of Atonement, feasts and holy days, and the Year of Jubilee. The central message is that God is holy and he requires his people to be holy. The book also shows that God graciously provides atonement for sin through the shedding of blood. Traditionally, Jews and Christians recognize Moses as the author, writing sometime after the giving of the Law.</p>
	</book>
	<book title="Numbers" num="4">
		<p>The English title &ldblquot;Numbers&rdblquot; comes from the two censuses that are central features of this book. However the Hebrew title, &ldblquot;In the Wilderness,&rdblquot; is more descriptive of the book. Numbers tells how God&apos;s people traveled from Mount Sinai to the border of the Promised Land. But when they refused to take possession of the Land, God made them wander in the wilderness for nearly forty years. Throughout the book, God is seen as a holy God who cannot ignore rebellion or unbelief, but also as the one who faithfully keeps his covenant and patiently provides for the needs of his people. Numbers ends with a new generation preparing for the conquest of Canaan. Traditionally, Jews and Christians recognize Moses as the author, writing during the final year of his life.</p>
	</book>
	<book title="Deuteronomy" num="5">
		<p>Deuteronomy, which means &ldblquot;second law,&rdblquot; is a retelling by Moses of the teachings and events of Exodus, Leviticus, and Numbers. It includes an extended review of the Ten Commandments (4:44&emdash;5:33) and Moses&apos; farewell address to a new generation of Israelites as they stand ready to take possession of the Promised Land. Moses reminds them of God&apos;s faithfulness and love, but also of God&apos;s wrath on the previous generation of Israelites because of their rebellion. Repeatedly he charges Israel to keep the Law. Deuteronomy is a solemn call to love and obey the one true God. There are blessings for faithfulness and curses for unfaithfulness. The book closes with the selection of Joshua as Israel&apos;s new leader and the death of Moses.</p>
	</book>
	<book title="Joshua" num="6">
		<p>The five books of Moses anticipated the fulfillment of God&apos;s promise to Abraham regarding the Promised Land. Now (either about 1400 or 1220 <span class="chronology">BC</span>), through a string of military victories under Joshua, Israel conquered the land and divided it among the twelve tribes. In these battles it became evident that God fights for his people when they are &ldblquot;strong and courageous&rdblquot; (1:6, 7, 9, 18; 10:25) and put their full trust in him. At the close of the book, Joshua charged the people to remain faithful to God and to obey his commands, and the people agreed to do so. &ldblquot;As for me and my house,&rdblquot; said Joshua, &ldblquot;we will serve the <span class="divine-name">Lord</span>&rdblquot; (24:15). Although anonymous, the book appears to contain eyewitness testimony, some of which may have been written by Joshua himself.</p>
	</book>
	<book title="Judges" num="7">
		<p>Judges is named after an interesting collection of individuals who led Israel after Joshua&apos;s death until the rise of the monarchy under Samuel (up to about 1050 <span class="chronology">BC</span>). In this time of national decline, despite their promise to keep the covenant (Josh. 24:16&endash;18) the people turned from the Lord and began to worship other gods. &ldblquot;Everyone did what was right in his own eyes&rdblquot; (Judg. 17:6; 21:25). A pattern repeats throughout the book: (1) the people abandoned the Lord; (2) God punished them by raising up a foreign power to oppress them; (3) the people cried out to God for deliverance; and (4) God raised up a deliverer, or judge, for them. The author of the book is unknown, although some Jewish tradition ascribes it to Samuel.</p>
	</book>
	<book title="Ruth" num="8">
		<p>The book of Ruth tells of a young Moabite widow who, out of love for her widowed Israelite mother-in-law, abandoned her own culture, declaring, &ldblquot;Your people shall be my people, and your God my God&rdblquot; (1:16). Though she was destitute and needing to rely on the kindness of others, Ruth&apos;s disposition and character captured the attention of Boaz, a close relative of her deceased husband. Boaz fulfilled the role of kinsman-redeemer and took Ruth as his wife. Ruth serves as a wonderful example of God&apos;s providential care of his people, and of his willingness to accept Gentiles who seek him. Ruth was an ancestor of Christ. The author is unknown, but the genealogy at the end suggests that it was written during or after the time of David.</p>
	</book>
	<book title="First Samuel" num="9">
		<p>First Samuel records the establishment of Israel&apos;s monarchy, about 1050 <span class="chronology">BC</span>. Samuel led Israel for many years in the combined roles of prophet, priest, and judge. After the people demanded a king like those of the other nations (ch. 8), God directed Samuel to anoint Saul as Israel&apos;s first king. When Saul turned from God, David was anointed by Samuel to succeed him. After David killed the giant Goliath, he was brought to Saul&apos;s court, eventually becoming the leader of Saul&apos;s armies. Saul&apos;s subsequent violent jealousy forced David to flee. The book closes with Saul&apos;s death in battle, and looks forward to David&apos;s reign. First Samuel&apos;s author is unknown, but Samuel himself may have written portions of the book (see 1 Chron. 29:29).</p>
	</book>
	<book title="Second Samuel" num="10">
		<p>Second Samuel recounts David&apos;s reign as king of Israel (about 1010&endash;970 <span class="chronology">BC</span>). As promised to Abraham, during David&apos;s reign Israel&apos;s borders were extended roughly from Egypt to the Euphrates. While David had many successes, after his sin against Bathsheba and Uriah (ch. 11) both his kingdom and his own family fell into chaos. His son Absalom led a bloody rebellion against him. Nevertheless David, author of many of the Psalms, was a man after God&apos;s own heart (Acts 13:22), a model of deep, heartfelt prayer and repentance. The Davidic Covenant of chapter 7 establishes the eternal rule of David&apos;s line, with its ultimate fulfillment in the coming of Jesus Christ. The author of 2 Samuel is unknown.</p>
	</book>
	<book title="First Kings" num="11">
		<p>First Kings begins with the death of King David (about 970 <span class="chronology">BC</span>) and the reign of his son, Solomon, who &ldblquot;excelled all the kings of the earth in riches and in wisdom&rdblquot; (10:23). Solomon&apos;s unfaithfulness later in life set the stage for general apostasy among the people. The harsh policies of his son Rehoboam led to the revolt of the northern tribes and the division of Israel. The northern tribes would subsequently be called Israel, while the southern tribes would be called Judah. First Kings describes the construction of the temple in Jerusalem and shows the importance of proper worship. God&apos;s faithfulness to his people is shown as he sent prophets, most notably Elijah, to warn them not to serve other gods. The author of 1 Kings is unknown.</p>
	</book>
	<book title="Second Kings" num="12">
