=== blocher/dailyoffice2019/site/esv/schema/crossway.crossrefs.dtd
<!--
match="..." is an XPath expression indicating which elements in the Bible text
XML files the crossrefs correspond to
-->
<!ELEMENT crossway-crossrefs (book)+>
<!ATTLIST crossway-crossrefs  translation CDATA #REQUIRED
                              edition CDATA #REQUIRED
                              match CDATA #REQUIRED
                              revision CDATA #REQUIRED>

<!--
title="..." is the friendly name of the book
-->
<!ELEMENT book (chapter)+>
<!ATTLIST book  num CDATA #REQUIRED
                title CDATA #IMPLIED>

<!--
id="..." is unique in a given document; not ID because it starts with a number;
title="..." is what to print to recreate the text as it appears in the printed Bibles
-->
<!ELEMENT chapter (verse)+>
<!ATTLIST chapter  id CDATA #REQUIRED
                   title CDATA #IMPLIED>

<!--
id="..." is not unique; Psalm titles share an id with the first verse in the Psalm;
title="..." is what to print to recreate the text as it appears in printed Bibles
-->
<!ELEMENT verse (letter)+>
<!ATTLIST verse  id CDATA #REQUIRED
                 title CDATA #IMPLIED>

<!--
id="..." is unique in a given document; CDATA, not ID, because it starts with a number;
title="..." is what to print to recreate the text as it appears in printed Bibles
-->
<!ELEMENT letter (text,cids,refs)>
<!ATTLIST letter  id CDATA #REQUIRED
                  title CDATA #IMPLIED>

<!--
contains only one or more <cid> elements
-->
<!ELEMENT cids (cid)+>

<!--
"cid" is an attribute used in the text of the Bible to uniquely identify a crossref
letter; the same letter can appear more than once in the text, but it only has
one entry in the crossref; each <cid> contains the cid of exactly one letter;
there can be any number of <cid>s for a given <letter>
-->
<!ELEMENT cid (#PCDATA)>

<!--
contains the plain text of the crossref; use if you're just doing print typesetting
-->
<!ELEMENT text (#PCDATA)>

<!--
cite="..." refers to a <letter> id; you can always substitute the content of the current
letter with that of the cited letter; it's CDATA, not IDREF, because the <letter> id
starts with a number; the <ref>s inside a <refs> with "cite" always just say something
like, "[See ver. 13 above]"; printed Bibles use this construction to save space

you can recreate the text in the <text> element by stripping out all the whitespace
between the tags and then stripping out the tags themselves
-->
<!ELEMENT refs (ref|meta)+>
<!ATTLIST refs  cite CDATA #IMPLIED>

<!--
<ref> can contain <meta>s only with class="separator-weak|same-book|same-chapter"

for="..." is usually an 8-digit number: the first 2 digits are the book (01-66),
the next three digits are the chapter (001-150), and the final three digits are
the verse (001-176); for example, "43003016" is "John 3:16"; sometimes there will
only be a 5-digit number, signifying the book and chapter: this happens when the
passage referred to is a complete chapter; for example, "01003" is "Genesis 3";
sometimes there's a range of verses indicated, so there will be two 8- or 5-digit
numbers separated by a hyphen; in the case of a 5-digit number, the range goes
from the beginning of the first verse in the first indicated chapter to the last
verse in the second indicated chapter; for example, "02010015-02012016" is
"Exodus 10:15-Exodus 12:16"; "40005-40007" is "Matthew 5:1-Matthew 7:29"
or "Matthew 5-Matthew 7"

consecutive verses (eg, "Col. 1:16, 17" in Gen 1:1 in the Cross Reference db)
are contained inside one <ref> with a range in the "for" attribute; printed
Bibles follow this style; a <meta class="separator-weak"> always appears in
such a case; you could replace the <meta> element with a hyphen if you prefer
to use that style
-->
<!ELEMENT ref (#PCDATA|meta)*>
<!ATTLIST ref  for CDATA #REQUIRED>

<!--
class="see-parallel|see-parallels" only appear in the text-only crossrefs;
"for|or|gk" appear in both

above: coupled with "see" to point to the text of another crossref;
begin-theme: the beginning of a thematic crossref, signified with "[" in
	printed Bibles;
cited: this verse is cited somewhere else (given in the following <ref>s);
cited-from: this verse contains a quotation of another verse (given in
	the following <ref>s);
end-theme: the end of a thematic crossref, signified with "]" in printed
	Bibles;
for: coupled with "see" to indicate that the <ref>s following "see" apply
	to a range of nearby verses, not just the current verse; the <ref>s
	following "for" but before "see" indicate the nearby verses;
gk|heb|heb-gk: the crossref is clearer in the original language; appears
	following the indicated verses;
or: only occurs once (John 15:25); indicates that the quotation could be
	from either of the verses (one before the "or" and one after);
same-book: appears as "ch. " in printed Bibles to save room;
same-chapter: appears as "ver. " in printed Bibles to save room;
see: appears either on its own to indicate a less-direct reference or
	coupled with "for"; the PCDATA can start with a comma in the latter case;
see-parallel: only in the text-only crossrefs; indicates a parallel Gospel
	passage;
see-parallels: only in the text-only crossrefs; like "see-parallel", but
	it means <ref>s from different books follow;
separator: "; " in printed Bibles; has several uses; appears only outside
	<ref>s; separates <ref>s of different chapters or books; separates
	elements in <refs>: eg, when there have been normal <ref>s and now there
	are going to be thematic refs, this separator appears
	(eg, "Matt. 1:1; [Matt. 2:6]");
separator-weak: ", " in printed Bibles; separates <ref>s of the same chapter;
	can appear inside a <ref> if it separates consecutive verses, eg:
		<ref for="...">Col. 1:16<meta class="separator-weak">, </meta>17</ref>
	Commas can appear outside this element, eg, as part of the
	PCDATA of other <meta>s; commas are also used to indicate the title of
	a Psalm: "Ps. 3, title"; in this case nothing surrounds the comma
	because it's integral to the <ref>;
with: the <ref>s before the "with" make more sense when coupled with
	the <ref>s after the "with"
-->
<!ELEMENT meta (#PCDATA)>
<!ATTLIST meta  class (above|begin-theme|cited|cited-from|end-theme|for|gk|heb|heb-gk|or|same-book|same-chapter|see|see-parallel|see-parallels|separator|separator-weak|with) #REQUIRED>

<!--
"endash" is used when a citation crosses a chapter boundary: "John 3:16-18" vs.
"John 3:16&endash;4:1"; you can substitute a hyphen for an endash if it isn't
important in your application to be typographically correct
-->
<!ENTITY  endash "&#8211;">

=== blocher/dailyoffice2019/site/esv/_crossrefs.toe.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE crossway-crossrefs SYSTEM "schema/crossway.crossrefs.dtd">
<crossway-crossrefs translation="English Standard Version" edition="Text Only" match="//crossref[(starts-with(@cid, 't')]" revision="2025-02-02">
<book num="40">
	<chapter id="40001">
		<verse id="40001023">
			<letter id="40001023.1">
				<text>Isa. 7:14</text>
				<cids><cid>t40001023.1</cid></cids>
				<refs>
					<ref for="23007014">Isa. 7:14</ref>
				</refs>
			</letter>
		</verse>
	</chapter>
	<chapter id="40002">
		<verse id="40002006">
			<letter id="40002006.1">
				<text>Mic. 5:2</text>
				<cids><cid>t40002006.1</cid></cids>
				<refs>
					<ref for="33005002">Mic. 5:2</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40002015">
			<letter id="40002015.1">
				<text>Hos. 11:1</text>
				<cids><cid>t40002015.1</cid></cids>
				<refs>
					<ref for="28011001">Hos. 11:1</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40002018">
			<letter id="40002018.1">
				<text>Jer. 31:15</text>
				<cids><cid>t40002018.1</cid></cids>
				<refs>
					<ref for="24031015">Jer. 31:15</ref>
				</refs>
			</letter>
		</verse>
	</chapter>
	<chapter id="40003">
		<verse id="40003001">
			<letter id="40003001.1">
				<text>For 3:1-12 see parallels Mark 1:2-8; Luke 3:1-17</text>
				<cids><cid>t40003001.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40003001-40003012">3:1-12</ref>
					<meta class="see-parallels"> see parallels </meta>
					<ref for="41001002-41001008">Mark 1:2-8</ref>
					<meta class="separator">; </meta>
					<ref for="42003001-42003017">Luke 3:1-17</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40003003">
			<letter id="40003003.1">
				<text>Isa. 40:3</text>
				<cids><cid>t40003003.1</cid></cids>
				<refs>
					<ref for="23040003">Isa. 40:3</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40003013">
			<letter id="40003013.1">
				<text>For 3:13-17 see parallels Mark 1:9-11; Luke 3:21, 22</text>
				<cids><cid>t40003013.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40003013-40003017">3:13-17</ref>
					<meta class="see-parallels"> see parallels </meta>
					<ref for="41001009-41001011">Mark 1:9-11</ref>
					<meta class="separator">; </meta>
					<ref for="42003021-42003022">Luke 3:21<meta class="separator-weak">, </meta>22</ref>
				</refs>
			</letter>
		</verse>
	</chapter>
	<chapter id="40004">
		<verse id="40004001">
			<letter id="40004001.1">
				<text>For 4:1-11 see parallels Mark 1:12, 13; Luke 4:1-13</text>
				<cids><cid>t40004001.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40004001-40004011">4:1-11</ref>
					<meta class="see-parallels"> see parallels </meta>
					<ref for="41001012-41001013">Mark 1:12<meta class="separator-weak">, </meta>13</ref>
					<meta class="separator">; </meta>
					<ref for="42004001-42004013">Luke 4:1-13</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40004004">
			<letter id="40004004.1">
				<text>Deut. 8:3</text>
				<cids><cid>t40004004.1</cid></cids>
				<refs>
					<ref for="05008003">Deut. 8:3</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40004006">
			<letter id="40004006.1">
				<text>Ps. 91:11, 12</text>
				<cids><cid>t40004006.1</cid></cids>
				<refs>
					<ref for="19091011-19091012">Ps. 91:11<meta class="separator-weak">, </meta>12</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40004007">
			<letter id="40004007.1">
				<text>Deut. 6:16</text>
				<cids><cid>t40004007.1</cid></cids>
				<refs>
					<ref for="05006016">Deut. 6:16</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40004010">
			<letter id="40004010.1">
				<text>Deut. 6:13</text>
				<cids><cid>t40004010.1</cid></cids>
				<refs>
					<ref for="05006013">Deut. 6:13</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40004015">
			<letter id="40004015.1">
				<text>Isa. 9:1, 2</text>
				<cids><cid>t40004015.1</cid></cids>
				<refs>
					<ref for="23009001-23009002">Isa. 9:1<meta class="separator-weak">, </meta>2</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40004018">
			<letter id="40004018.1">
				<text>For 4:18-22 see parallel Mark 1:16-20</text>
				<cids><cid>t40004018.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40004018-40004022">4:18-22</ref>
					<meta class="see-parallel"> see parallel </meta>
					<ref for="41001016-41001020">Mark 1:16-20</ref>
				</refs>
			</letter>
		</verse>
	</chapter>
	<chapter id="40005">
		<verse id="40005021">
			<letter id="40005021.1">
				<text>Ex. 20:13; Deut. 5:17</text>
				<cids><cid>t40005021.1</cid></cids>
				<refs>
					<ref for="02020013">Ex. 20:13</ref>
					<meta class="separator">; </meta>
					<ref for="05005017">Deut. 5:17</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40005027">
			<letter id="40005027.1">
				<text>Ex. 20:14; Deut. 5:18</text>
				<cids><cid>t40005027.1</cid></cids>
				<refs>
					<ref for="02020014">Ex. 20:14</ref>
					<meta class="separator">; </meta>
					<ref for="05005018">Deut. 5:18</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40005031">
			<letter id="40005031.1">
				<text>Deut. 24:1</text>
				<cids><cid>t40005031.1</cid></cids>
				<refs>
					<ref for="05024001">Deut. 24:1</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40005038">
			<letter id="40005038.1">
				<text>Ex. 21:24; Lev. 24:20; Deut. 19:21</text>
				<cids><cid>t40005038.1</cid></cids>
				<refs>
					<ref for="02021024">Ex. 21:24</ref>
					<meta class="separator">; </meta>
					<ref for="03024020">Lev. 24:20</ref>
					<meta class="separator">; </meta>
					<ref for="05019021">Deut. 19:21</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40005039">
			<letter id="40005039.1">
				<text>For 5:39-42 see parallel Luke 6:29, 30</text>
				<cids><cid>t40005039.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40005039-40005042">5:39-42</ref>
					<meta class="see-parallel"> see parallel </meta>
					<ref for="42006029-42006030">Luke 6:29<meta class="separator-weak">, </meta>30</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40005043">
			<letter id="40005043.1">
				<text>Lev. 19:18</text>
				<cids><cid>t40005043.1</cid></cids>
				<refs>
					<ref for="03019018">Lev. 19:18</ref>
				</refs>
			</letter>
		</verse>
	</chapter>
	<chapter id="40006">
		<verse id="40006025">
			<letter id="40006025.1">
				<text>For 6:25-33 see parallel Luke 12:22-31</text>
				<cids><cid>t40006025.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40006025-40006033">6:25-33</ref>
					<meta class="see-parallel"> see parallel </meta>
					<ref for="42012022-42012031">Luke 12:22-31</ref>
				</refs>
			</letter>
		</verse>
	</chapter>
	<chapter id="40007">
		<verse id="40007001">
			<letter id="40007001.1">
				<text>For 7:1-5 see parallel Luke 6:37, 38, 41, 42</text>
				<cids><cid>t40007001.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40007001-40007005">7:1-5</ref>
					<meta class="see-parallel"> see parallel </meta>
					<ref for="42006037-42006038">Luke 6:37<meta class="separator-weak">, </meta>38</ref>
					<meta class="separator-weak">, </meta>
					<ref for="42006041-42006042">41<meta class="separator-weak">, </meta>42</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40007007">
			<letter id="40007007.1">
				<text>For 7:7-11 see parallel Luke 11:9-13</text>
				<cids><cid>t40007007.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40007007-40007011">7:7-11</ref>
					<meta class="see-parallel"> see parallel </meta>
					<ref for="42011009-42011013">Luke 11:9-13</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40007024">
			<letter id="40007024.1">
				<text>For 7:24-27 see parallel Luke 6:47-49</text>
				<cids><cid>t40007024.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40007024-40007027">7:24-27</ref>
					<meta class="see-parallel"> see parallel </meta>
					<ref for="42006047-42006049">Luke 6:47-49</ref>
				</refs>
			</letter>
		</verse>
	</chapter>
	<chapter id="40008">
		<verse id="40008002">
			<letter id="40008002.1">
				<text>For 8:2-4 see parallels Mark 1:40-44; Luke 5:12-14</text>
				<cids><cid>t40008002.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40008002-40008004">8:2-4</ref>
					<meta class="see-parallels"> see parallels </meta>
					<ref for="41001040-41001044">Mark 1:40-44</ref>
					<meta class="separator">; </meta>
					<ref for="42005012-42005014">Luke 5:12-14</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40008005">
			<letter id="40008005.1">
				<text>For 8:5-13 see parallel Luke 7:1-10</text>
				<cids><cid>t40008005.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40008005-40008013">8:5-13</ref>
					<meta class="see-parallel"> see parallel </meta>
					<ref for="42007001-42007010">Luke 7:1-10</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40008014">
			<letter id="40008014.1">
				<text>For 8:14-17 see parallels Mark 1:29-34; Luke 4:38-41</text>
				<cids><cid>t40008014.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40008014-40008017">8:14-17</ref>
					<meta class="see-parallels"> see parallels </meta>
					<ref for="41001029-41001034">Mark 1:29-34</ref>
					<meta class="separator">; </meta>
					<ref for="42004038-42004041">Luke 4:38-41</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40008017">
			<letter id="40008017.1">
				<text>Isa. 53:4</text>
				<cids><cid>t40008017.1</cid></cids>
				<refs>
					<ref for="23053004">Isa. 53:4</ref>
				</refs>
			</letter>
		</verse>
		<verse id="40008019">
			<letter id="40008019.1">
				<text>For 8:19-22 see parallel Luke 9:57-62</text>
				<cids><cid>t40008019.1</cid></cids>
				<refs>
					<meta class="for">For </meta>
					<ref for="40008019-40008022">8:19-22</ref>
