=== blocher/dailyoffice2019/site/esv/schema/crossway.notes.dtd
<!--
match="..." is an XPath expression indicating which elements in the Bible text
  XML files the notes correspond to
  -->
<!ELEMENT crossway-notes (book)+>
<!ATTLIST crossway-notes  translation CDATA #REQUIRED
                          match CDATA #REQUIRED
                          revision CDATA #REQUIRED
                          xmlns:xsi CDATA #IMPLIED
                          xmlns CDATA #IMPLIED
                          xsi:schemaLocation CDATA #IMPLIED>

<!ELEMENT book (note)+>
<!ATTLIST book  title CDATA #REQUIRED
                num  CDATA #REQUIRED>

<!ELEMENT note (#PCDATA|i|span|a|note-verse)*>
<!ATTLIST note  id ID #REQUIRED
                class CDATA #IMPLIED
                sub-class CDATA #IMPLIED>

<!--
<i> indicates italic text
-->
<!ELEMENT i (#PCDATA|span|note-verse)*>
<!ATTLIST i  class CDATA #IMPLIED
             language CDATA #IMPLIED>

<!--
<span>s with class="divine-name|us-time|small-caps" should be converted
  to small caps; other <span>s don't need transformation
-->
<!ELEMENT span (#PCDATA|span)*>
<!ATTLIST span  class CDATA #IMPLIED
                language CDATA #IMPLIED>

<!ELEMENT a (#PCDATA)*>
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT note-verse (#PCDATA)*>

<!ENTITY ldblquot  "&#8220;">
<!ENTITY rdblquot  "&#8221;">
<!ENTITY lquot     "&#8216;">
<!ENTITY rquot     "&#8217;">
<!ENTITY emdash    "&#8212;">
<!ENTITY endash    "&#8211;">
<!ENTITY ellipsis  "&#160;.&#160;.&#160;.">
<!ENTITY ellipsis4 ".&#160;.&#160;.&#160;.">
<!ENTITY emacron   "&#275;">

=== blocher/dailyoffice2019/site/bible/esv/_notes.text.apocrypha.xml
<?xml version='1.0' standalone='no'?>
<!DOCTYPE crossway-notes SYSTEM "schema/crossway.notes.dtd">
<crossway-notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" translation="English Standard Version" match="//note[starts-with(@nid, 'n')]" revision="2018-3-26" xmlns="http://www.crosswaybibles.org" xsi:schemaLocation="schema/crossway.bibles.xsd">
   <book title="Tobit" num="70">
      <note id="n70001002.1">Latin <i>Enemessar</i>; also verses 13, 15, 16</note>
      <note id="n70001002.2">Greek <i>right</i></note>
      <note id="n70001002.3">Greek <i>left</i></note>
      <note id="n70001004.1">Greek <i>father</i>; twice, and also verse 5</note>
      <note id="n70001010.1">Greek <i>bread</i>; also verse 11</note>
      <note id="n70001012.1">Latin; Greek <i>when</i></note>
      <note id="n70001021.1">Some manuscripts <i>forty-five</i> or <i>fifty</i></note>
      <note id="n70001021.2">Greek <i>his</i></note>
      <note id="n70001021.3">Greek <i>Sacherdonus</i>; also verse 22</note>
      <note id="n70001022.1">Or <i>him a second time</i></note>
      <note id="n70002001.1">Greek <i>Sacherdonus</i></note>
      <note id="n70002002.1">Greek <i>brothers</i>; also verse 3</note>
      <note id="n70002004.1">Greek <i>him</i></note>
      <note id="n70002004.2">Greek <i>him</i></note>
      <note id="n70002010.1">Greek <i>brothers</i></note>
      <note id="n70002012.1">Greek <i>for the hearth</i></note>
      <note id="n70003002.1">Or <i>age</i></note>
      <note id="n70003003.1">Or <i>look down upon me</i></note>
      <note id="n70003015.1">Greek <i>brother</i></note>
      <note id="n70004003.1">Greek <i>he</i></note>
      <note id="n70004004.1">Tobit 4:5&endash;19 is supplied from Greek Vaticanus (see Preface to the Apocrypha); Greek Sinaiticus reads: <note-verse>5</note-verse><i>&ldblquot;Remember the Lord all your days, child, and refuse to sin or to transgress his commandments. Do righteous deeds all the days of your life and do not walk in the paths of wrongdoing. </i><note-verse>6</note-verse><i>For those who practice what is true will prosper in their deeds. </i><note-verse>7</note-verse><i>And to all who practice righteousness, </i><note-verse>19</note-verse><i>the Lord will give them good counsel, and whomever the Lord wishes he brings down as far as Hades below.</i></note>
      <note id="n70004019.1">Greek <i>heart</i></note>
      <note id="n70004020.1">Greek lacks <i>the brother</i>, but see 1:14</note>
      <note id="n70005002.1">Greek <i>it</i></note>
      <note id="n70005004.1">Greek <i>he</i></note>
      <note id="n70005005.1">Greek <i>he</i></note>
      <note id="n70005005.2">Greek <i>he</i></note>
      <note id="n70005007.1">Greek <i>he</i></note>
      <note id="n70005010.1">Greek <i>he</i></note>
      <note id="n70005011.1">Greek <i>he</i></note>
      <note id="n70005012.1">Greek <i>he</i></note>
      <note id="n70005014.1">Greek <i>he</i></note>
      <note id="n70005014.2">Greek <i>brothers</i></note>
      <note id="n70005017.1">Greek <i>he</i></note>
      <note id="n70006013.1">Greek <i>said</i></note>
      <note id="n70006015.1">Greek lacks <i>and I am afraid</i></note>
      <note id="n70006016.1">Greek <i>he</i></note>
      <note id="n70007002.1">Greek <i>brother</i>; also verse 7</note>
      <note id="n70007010.1">Greek omits <i>kin</i></note>
      <note id="n70007012.1">Greek <i>him</i></note>
      <note id="n70007015.1">Greek <i>her</i></note>
      <note id="n70008004.1">Greek <i>her</i></note>
      <note id="n70009005.1">Greek <i>him</i></note>
      <note id="n70009005.2">Greek <i>he</i></note>
      <note id="n70009006.1">Greek <i>he</i></note>
      <note id="n70010001.1">Greek <i>he</i></note>
      <note id="n70010006.1">Greek <i>he is already here</i></note>
      <note id="n70010012.1">The main Greek manuscript lacks <i>and your mother-in-law</i></note>
      <note id="n70010012.2">Greek <i>my daughter Sarah</i></note>
      <note id="n70010013.1">Greek uncertain</note>
      <note id="n70011005.1">Greek <i>her son&apos;s road</i></note>
      <note id="n70011009.1">Greek <i>I will die</i></note>
      <note id="n70011011.1">Greek <i>he yielded</i></note>
      <note id="n70011013.1">Greek lacks <i>the white films</i></note>
      <note id="n70011015.1">Greek <i>with his whole mouth</i></note>
      <note id="n70011017.1">The main Greek manuscript lacks <i>and your mother</i></note>
      <note id="n70011018.1">Some manuscripts <i>Nabad</i></note>
      <note id="n70011019.1">Some manuscripts and versions omit parts of verse 19 beginning at <i>The wedding was celebrated</i></note>
      <note id="n70012006.1">Greek <i>Then he</i></note>
      <note id="n70012014.1">Greek <i>bride</i></note>
      <note id="n70012019.1">Greek <i>that</i></note>
      <note id="n70013001.1">Greek <i>he</i></note>
      <note id="n70013006.1">Greek <i>with your whole mouth</i></note>
      <note id="n70013006.2">Tobit 13:6<i>b</i>&endash;10<i>a</i> is supplied from Greek Vaticanus; see Preface to the Apocrypha.</note>
      <note id="n70013011.1">Greek lacks second <i>will come</i></note>
      <note id="n70013016.1">Greek <i>his</i></note>
      <note id="n70013017.1">Or <i>be inlaid with</i></note>
      <note id="n70014002.1">Greek <i>good things</i></note>
      <note id="n70014004.1">Latin; Greek <i>Athour</i></note>
      <note id="n70014004.2">Or <i>safety</i></note>
      <note id="n70014004.3">Latin; Greek <i>numbered</i></note>
      <note id="n70014006.1">Correction; Greek <i>who</i></note>
      <note id="n70014015.1">Greek <i>Achiachar</i></note>
      <note id="n70014015.2">Latin; Greek <i>Athouria</i></note>
   </book>
   <book title="Judith" num="71">
      <note id="n71001011.1">Or <i>a</i></note>
      <note id="n71002002.1">The meaning of the Greek is uncertain</note>
      <note id="n71002007.1">Greek <i>by them</i></note>
      <note id="n71002022.1">Greek <i>he</i></note>
      <note id="n71002024.1">Or <i>crossed</i></note>
      <note id="n71003008.1">Greek <i>borders</i></note>
      <note id="n71006003.1">Greek <i>we his servants</i></note>
      <note id="n71006006.1">Latin, Syriac; Greek <i>people</i></note>
      <note id="n71008012.1">Or <i>yourselves above</i></note>
      <note id="n71008021.1">Greek <i>of our blood</i></note>
      <note id="n71010001.1">Greek <i>she</i></note>
      <note id="n71010008.1">Some manuscripts <i>they</i></note>
      <note id="n71010011.1">Greek <i>They</i></note>
      <note id="n71010023.1">Greek <i>him</i></note>
      <note id="n71011019.1">Or <i>chariot</i></note>
      <note id="n71015005.1">Greek <i>upon them</i></note>
      <note id="n71016001.1">Some manuscripts <i>him a psalm and praise</i></note>
      <note id="n71016011.1">Some manuscripts <i>feared</i></note>
      <note id="n71016014.1">Or <i>breath</i></note>
   </book>
   <book title="Esther" num="72">
      <note id="n72000001a.1" class="deutero">In addition to the canonical book of Esther<pageref> (see pp. 410 to 416)</pageref>, the book of Esther appears here in the Apocrypha section of the ESV with Apocrypha, with the additional chapters and verses that are included in the Greek Septuagint version of the Esther text. The following three paragraphs in italic type, under the heading <i>Mordecai’s Dream</i>, do not appear in the Hebrew text of Esther. These three paragraphs, however, are included in the Greek Septuagint text of Esther and were likewise included in the Latin Vulgate version of the Bible translated by Jerome in the late fourth century AD. Jerome placed these paragraphs at the end of Esther, along with explanatory notes to make them accessible to the reader. For the text of Esther in this publication of the ESV Catholic Edition Bible, these paragraphs have been placed in the narrative sequence as they appear in the Septuagint. The paragraphs under this heading (<i>Mordecai’s Dream</i>) correspond to the following chapter and verse numbers used in the Vulgate: Esther 11:2–12. See further, the <i>Preface to the Apocrypha</i><pageref>, pp. 1047–1048</pageref>.</note>
      <note id="n72000001m.1" class="deutero">The following paragraph in italic type, under the heading <i>Plot against the King</i>, does not appear in the Hebrew text of Esther. This paragraph, however, is included in the Greek Septuagint and the Latin Vulgate, where it corresponds to the following chapter and verse numbers used in the Vulgate: Esther 12:1–6. See further the asterisk note above and the <i>Preface to the Apocrypha</i><pageref>, pp. 1047–1048</pageref>.</note>
      <note id="n72001006.1" class="alternative">Or <i>rings</i></note>
      <note id="n72001011.1" class="alternative">Or <i>headdress</i></note>
      <note id="n72001017.1" class="translation" sub-class="original">Hebrew <i>to disdain their husbands in their eyes</i></note>
      <note id="n72002004.1" class="translation" sub-class="original">Hebrew <i>who is good in the eyes of the king</i></note>
      <note id="n72002017.1" class="alternative">Or <i>headdress</i></note>
      <note id="n72002023.1" class="background" sub-class="culture">Or <i>wooden beam</i> or <i>stake</i>; Hebrew <i>tree</i> or <i>wood</i>. This Persian execution practice involved affixing or impaling a person on a stake or pole (compare Ezra 6:11)</note>
      <note id="n72003006.1" class="translation" sub-class="original">Hebrew <i>disdained in his eyes</i></note>
      <note id="n72003006.2" class="alternative">Or <i>annihilate</i></note>
      <note id="n72003009.1" class="background" sub-class="measurement">A <i class="catch-word-plural">talent</i> was about 75 pounds or 34 kilograms</note>
