=== blocher/dailyoffice2019/site/bible/esv/schema/crossway.bibles.dtd
<!ELEMENT crossway-bible (book)+>
<!ATTLIST crossway-bible  translation CDATA #REQUIRED
                          revision CDATA #REQUIRED
                          xmlns:xsi CDATA #IMPLIED
                          xmlns CDATA #IMPLIED
                          xsi:schemaLocation CDATA #IMPLIED>

<!ELEMENT book (chapter|heading|marker)+>
<!ATTLIST book  title CDATA #REQUIRED
                num CDATA #REQUIRED>

<!ELEMENT chapter (#PCDATA|begin-block-indent|begin-paragraph|end-block-indent|end-paragraph|heading|subheading|verse|marker|note)*>
<!ATTLIST chapter  num CDATA #REQUIRED>

<!ELEMENT subheading (#PCDATA|crossrefs|crossref|note|span|q)*>
<!ATTLIST subheading  class (psalm-acrostic-title|psalm-title|speaker|textual-note) #IMPLIED>

<!ELEMENT begin-block-indent EMPTY>
<!ELEMENT begin-paragraph    EMPTY>
<!ATTLIST begin-paragraph    class (same-paragraph|extra-space|line-group) #IMPLIED>
<!ELEMENT end-block-indent   EMPTY>
<!ELEMENT end-paragraph      EMPTY>

<!-- How far to indent -->
<!ELEMENT begin-line EMPTY>
<!ATTLIST begin-line class (indent|indent-2|declares|psalm-doxology) #IMPLIED>
<!-- class="br" indicates a line break -->
<!ELEMENT end-line   EMPTY>
<!ATTLIST end-line   class (br) #IMPLIED>

<!-- class="psalm-book" is only in the Psalms -->
<!ELEMENT heading (#PCDATA|span|note)*>
<!ATTLIST heading class (psalm-book) #IMPLIED>

<!ELEMENT verse  (#PCDATA|begin-paragraph|end-paragraph|begin-block-indent|end-block-indent|begin-line|end-line|span|note|crossrefs|crossref|woc|heading|subheading|selah|q|deutero)*>
<!ATTLIST verse   class (woc) #IMPLIED
                  num CDATA #REQUIRED
                  altnum CDATA #IMPLIED>

<!ELEMENT deutero (#PCDATA|begin-paragraph|end-paragraph|begin-block-indent|end-block-indent|begin-line|end-line|span|note|crossrefs|crossref|woc|heading|subheading|selah|q)*>

<!-- class="us-time" appears only in notes -->
<!ELEMENT span (#PCDATA)>
<!ATTLIST span  class (divine-name|us-time|small-caps) #IMPLIED>

<!ELEMENT selah (#PCDATA|note|crossrefs|crossref)*>

<!-- Words of Christ; never crosses a paragraph -->
<!ELEMENT woc (#PCDATA|span|note|begin-line|end-line|crossrefs|crossref|q)*>

<!-- contains two or more crossrefs that need to be separated by a comma
     (or a comma and space)-->
<!ELEMENT crossrefs (crossref)+>

<!ELEMENT crossref EMPTY>
<!ATTLIST crossref let CDATA #IMPLIED
                   cid ID #REQUIRED>

<!-- notes themselves contain (#PCDATA|a|i|verse-num|span)* -->
<!ELEMENT note EMPTY>
<!ATTLIST note nid CDATA #REQUIRED>

<!ELEMENT q EMPTY>
<!ATTLIST q class CDATA #REQUIRED
            qid CDATA #REQUIRED
            from CDATA #IMPLIED
            to CDATA #IMPLIED>

<!--
<marker> is designed to indicate the placement of
arbitrary data for various editions; the goal is to clutter the Bible XML files
as little as possible with a proliferation of non-Bible content;

mid="..." should use a unique alphabetic prefix that can be queried with XPath;
ideally, the rest of "mid" should be an 8-digit number indicating the verse where
it appears (or should be attached to; a book introduction would be part of the
first verse of the first chapter of the book

class="..." is optional and can be used to make it easier to determine the type
of marker; for example, a complete marker for an introduction to John in the
text-only edition might be:
	<marker class="intro" mid="it43001001"/>
In the cross-reference edition, it might be:
	<marker class="intro" mid="ic43001001"/>
Taken together, you would have the following fragment:
	<book title="John" num="43">
		<marker class="intro" mid="it43001001"/>
		<marker class="intro" mid="ic43001001"/>
		<chapter num="1">
			<heading>...etc...
-->
<!ELEMENT marker EMPTY>
<!ATTLIST marker class CDATA #IMPLIED
                 mid CDATA #REQUIRED>

<!-- link to preface for certain footnotes -->
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #IMPLIED>

<!-- italic text for certain footnotes -->
<!ELEMENT i (#PCDATA|span)*>

<!ELEMENT verse-num (#PCDATA)>

<!-- Entities -->
<!ENTITY ldblquot  "&#8220;">
<!ENTITY rdblquot  "&#8221;">
<!ENTITY lquot     "&#8216;">
<!ENTITY rquot     "&#8217;">
<!ENTITY emdash    "&#8212;">
<!ENTITY endash    "&#8211;">
<!ENTITY ellipsis  "&#160;.&#160;.&#160;.">
<!ENTITY ellipsis4 ".&#160;.&#160;.&#160;.">
<!ENTITY emacron   "&#275;">

=== blocher/dailyoffice2019/site/bible/esv/84.Psalm 151.xml
<?xml version='1.0' encoding='utf-8' standalone='yes'?>
<!DOCTYPE crossway-bible SYSTEM "schema/crossway.bibles.dtd">
<crossway-bible xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" translation="English Standard Version" revision="2018-3-26" xmlns="http://www.crosswaybibles.org" xsi:schemaLocation="schema/crossway.bibles.xsd">
  <book title="Psalm 151" num="84">
    <marker class="begin-verse" mid="v84001001"/>
    <chapter num="1">
      <subheading class="psalm-title">This psalm is ascribed to David as his own composition (though it is outside the number<note nid="n84001001.1"/>), after he had fought in single combat with Goliath.</subheading>
      <begin-block-indent/>
      <begin-paragraph class="line-group"/>
      <verse num="1"><begin-line/>I was small among my brothers<end-line class="br"/><begin-line class="indent"/>and youngest in my father<q class="end-single" qid="84001001.1"/>s house;<end-line class="br"/><begin-line/>I tended my father<q class="end-single" qid="84001001.2"/>s sheep.<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v84001002"/>
      <verse num="2"><begin-line/>My hands made a harp,<end-line class="br"/><begin-line class="indent"/>my fingers fashioned a lyre.<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v84001003"/>
      <verse num="3"><begin-line/>And who will declare it to my Lord?<end-line class="br"/><begin-line class="indent"/>The Lord himself; he himself listens.<note nid="n84001003.1"/><end-line class="br"/></verse>
      <marker class="begin-verse" mid="v84001004"/>
      <verse num="4"><begin-line/>It was he who sent his messenger<note nid="n84001004.1"/><end-line class="br"/><begin-line class="indent"/>and took me from my father<q class="end-single" qid="84001004.1"/>s sheep<end-line class="br"/><begin-line class="indent"/>and anointed me with his anointing oil.<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v84001005"/>
      <verse num="5"><begin-line/>My brothers were handsome and tall,<end-line class="br"/><begin-line class="indent"/>but the Lord was not satisfied with them.<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v84001006"/>
      <verse num="6"><begin-line/>I went out to meet the Philistine,<note nid="n84001006.1"/><end-line class="br"/><begin-line class="indent"/>and he cursed me by his idols.<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v84001007"/>
      <verse num="7"><begin-line/>But I drew his own sword;<end-line class="br"/><begin-line class="indent"/>I beheaded him and removed reproach from the children of Israel.<end-line/></verse>
      <end-paragraph/>
      <end-block-indent/>
    </chapter>
  </book>
</crossway-bible>

=== blocher/dailyoffice2019/site/bible/esv/Jude.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE crossway-bible SYSTEM "schema/crossway.bibles.dtd">
<crossway-bible translation="English Standard Version" revision="2025-02-02" xmlns="http://www.crosswaybibles.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="schema/crossway.bibles.xsd">
<book title="Jude" num="65">
  <marker class="begin-verse" mid="v65001001"/>
  <chapter num="1">
    <heading>Greeting</heading>
    <begin-paragraph/>
    <verse num="1">Jude, a servant<note nid="n65001001.1"/> of Jesus Christ and brother of James,
      <end-paragraph/>
      <begin-paragraph/><crossref let="a" cid="c65001001.1"/>To those who are called, <crossref let="b" cid="c65001001.2"/>beloved in God the Father and <crossref let="c" cid="c65001001.3"/>kept for<note nid="n65001001.2"/> Jesus Christ:
    </verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v65001002"/>
    <begin-paragraph/>
    <verse num="2">May <crossref let="d" cid="c65001002.1"/>mercy, <crossref let="e" cid="c65001002.2"/>peace, and love be multiplied to you.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v65001003"/>
    <heading>Judgment on False Teachers</heading>
    <begin-paragraph/>
    <verse num="3">Beloved, although I was very eager to write to you about our <crossref let="f" cid="c65001003.1"/>common salvation, I found it necessary to write appealing to you <crossref let="g" cid="c65001003.2"/>to contend for the faith that was once for all delivered to the saints.</verse>
    <marker class="begin-verse" mid="v65001004"/>
    <verse num="4">For <crossref let="h" cid="c65001004.1"/>certain people <crossref let="i" cid="c65001004.2"/>have crept in unnoticed <crossref let="j" cid="c65001004.3"/>who long ago were designated for this condemnation, ungodly people, who pervert <crossref let="k" cid="c65001004.4"/>the grace of our God into sensuality and <crossref let="l" cid="c65001004.5"/>deny our only Master and Lord, Jesus Christ.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v65001005"/>
    <begin-paragraph/>
    <verse num="5">Now I want <crossref let="m" cid="c65001005.1"/>to remind you, although you once fully knew it, that <crossref let="n" cid="c65001005.2"/>Jesus, who saved<note nid="n65001005.1"/> a people out of the land of Egypt, <crossref let="o" cid="c65001005.3"/>afterward destroyed those who did not believe.</verse>
    <marker class="begin-verse" mid="v65001006"/>
    <verse num="6">And <crossref let="p" cid="c65001006.1"/>the angels who did not stay within their own position of authority, but left their proper dwelling, he has kept in eternal chains under gloomy darkness until the judgment of the great day&emdash;</verse>
    <marker class="begin-verse" mid="v65001007"/>
    <verse num="7">just as <crossref let="q" cid="c65001007.1"/>Sodom and Gomorrah and <crossref let="r" cid="c65001007.2"/>the surrounding cities, which likewise indulged in sexual immorality and <crossref let="s" cid="c65001007.3"/>pursued unnatural desire,<note nid="n65001007.1"/> serve as an example by undergoing a punishment of eternal fire.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v65001008"/>
    <begin-paragraph/>
    <verse num="8">Yet in like manner these people also, relying on their dreams, defile the flesh, reject authority, and <crossref let="t" cid="c65001008.1"/>blaspheme the glorious ones.</verse>
    <marker class="begin-verse" mid="v65001009"/>
    <verse num="9">But when <crossref let="u" cid="c65001009.1"/>the archangel <crossref let="v" cid="c65001009.2"/>Michael, contending with the devil, was disputing <crossref let="w" cid="c65001009.3"/>about the body of Moses, he did not presume to pronounce a blasphemous judgment, but said, <crossref let="x" cid="c65001009.4"/><q class="begin-double" qid="65001009.1" from="65001009.1" to="65001009.2"/>The Lord rebuke you.<q class="end-double" qid="65001009.2" from="65001009.1" to="65001009.2"/></verse>
    <marker class="begin-verse" mid="v65001010"/>
    <verse num="10"><crossref let="y" cid="c65001010.1"/>But these people blaspheme all that they do not understand, and they are destroyed by all that they, like unreasoning animals, understand instinctively.</verse>
    <marker class="begin-verse" mid="v65001011"/>
    <verse num="11">Woe to them! For they walked in <crossref let="z" cid="c65001011.1"/>the way of Cain and abandoned themselves for the sake of gain <crossref let="a" cid="c65001011.2"/>to Balaam&apos;s error and <crossref let="b" cid="c65001011.3"/>perished in Korah&apos;s rebellion.</verse>
    <marker class="begin-verse" mid="v65001012"/>
    <verse num="12">These are hidden reefs<note nid="n65001012.1"/> <crossref let="c" cid="c65001012.1"/>at your love feasts, as they feast with you without fear, <crossref let="d" cid="c65001012.2"/>shepherds feeding themselves; <crossref let="e" cid="c65001012.3"/>waterless clouds, <crossref let="f" cid="c65001012.4"/>swept along by winds; fruitless trees in late autumn, twice dead, <crossref let="g" cid="c65001012.5"/>uprooted;</verse>
    <marker class="begin-verse" mid="v65001013"/>
    <verse num="13"><crossref let="h" cid="c65001013.1"/>wild waves of the sea, casting up the foam of <crossref let="i" cid="c65001013.2"/>their own shame; <crossref let="j" cid="c65001013.3"/>wandering stars, <crossref let="k" cid="c65001013.4"/>for whom the gloom of utter darkness has been reserved forever.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v65001014"/>
    <begin-paragraph/>
    <verse num="14">It was also about these that Enoch, <crossref let="l" cid="c65001014.1"/>the seventh from Adam, prophesied, saying, <crossref let="m" cid="c65001014.2"/><q class="begin-double" qid="65001014.1" from="65001014.1" to="65001015.1"/>Behold, the Lord comes with ten thousands of his holy ones,</verse>
    <marker class="begin-verse" mid="v65001015"/>
    <verse num="15"><crossref let="n" cid="c65001015.1"/>to execute judgment on all and to convict all the ungodly of all their deeds of ungodliness that they have <crossref let="o" cid="c65001015.2"/>committed in such an ungodly way, and of all <crossref let="p" cid="c65001015.3"/>the harsh things that ungodly sinners have spoken against him.<q class="end-double" qid="65001015.1" from="65001014.1" to="65001015.1"/></verse>
    <marker class="begin-verse" mid="v65001016"/>
    <verse num="16">These are grumblers, malcontents, <crossref let="q" cid="c65001016.1"/>following their own sinful desires; <crossref let="r" cid="c65001016.2"/>they are loud-mouthed boasters, <crossref let="s" cid="c65001016.3"/>showing favoritism to gain advantage.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v65001017"/>
    <heading>A Call to Persevere</heading>
    <begin-paragraph/>
    <verse num="17">But you must <crossref let="t" cid="c65001017.1"/>remember, beloved, the predictions of the apostles of our Lord Jesus Christ.</verse>
    <marker class="begin-verse" mid="v65001018"/>
    <verse num="18">They<note nid="n65001018.1"/> said to you, <crossref let="u" cid="c65001018.1"/><q class="begin-double" qid="65001018.1" from="65001018.1" to="65001018.2"/>In the last time there will be scoffers, following their own ungodly passions.<q class="end-double" qid="65001018.2" from="65001018.1" to="65001018.2"/></verse>
    <marker class="begin-verse" mid="v65001019"/>
    <verse num="19">It is these who cause divisions, worldly people, <crossref let="v" cid="c65001019.1"/>devoid of the Spirit.</verse>
    <marker class="begin-verse" mid="v65001020"/>
    <verse num="20">But you, beloved, <crossref let="w" cid="c65001020.1"/>building yourselves up in your most holy faith and <crossref let="x" cid="c65001020.2"/>praying in the Holy Spirit,</verse>
    <marker class="begin-verse" mid="v65001021"/>
    <verse num="21"><crossref let="y" cid="c65001021.1"/>keep yourselves in the love of God, <crossref let="z" cid="c65001021.2"/>waiting for the mercy of our Lord Jesus Christ that leads to eternal life.</verse>
    <marker class="begin-verse" mid="v65001022"/>
    <verse num="22">And have mercy on those who doubt;</verse>
    <marker class="begin-verse" mid="v65001023"/>
    <verse num="23">save others by <crossref let="a" cid="c65001023.1"/>snatching them out of <crossref let="b" cid="c65001023.2"/>the fire; to others show mercy <crossref let="c" cid="c65001023.3"/>with fear, hating even <crossref let="d" cid="c65001023.4"/>the garment<note nid="n65001023.1"/> stained by the flesh.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v65001024"/>
    <heading>Doxology</heading>
    <begin-paragraph/>
    <verse num="24"><crossref let="e" cid="c65001024.1"/>Now to him who is able <crossref let="f" cid="c65001024.2"/>to keep you from stumbling and <crossref let="g" cid="c65001024.3"/>to present you <crossref let="h" cid="c65001024.4"/>blameless before the presence of his glory with great joy,</verse>
    <marker class="begin-verse" mid="v65001025"/>
    <verse num="25">to <crossref let="i" cid="c65001025.1"/>the only God, our Savior, through Jesus Christ our Lord, <crossref let="j" cid="c65001025.2"/>be glory, majesty, dominion, and authority, before all time<note nid="n65001025.1"/> and now and forever. Amen.</verse>
    <end-paragraph/>
  </chapter>
</book>
</crossway-bible>

=== blocher/dailyoffice2019/site/bible/esv/3 John.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE crossway-bible SYSTEM "schema/crossway.bibles.dtd">
<crossway-bible translation="English Standard Version" revision="2025-02-02" xmlns="http://www.crosswaybibles.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="schema/crossway.bibles.xsd">
<book title="3 John" num="64">
  <marker class="begin-verse" mid="v64001001"/>
  <chapter num="1">
    <heading>Greeting</heading>
    <begin-paragraph/>
    <verse num="1"><crossref let="a" cid="c64001001.1"/>The elder to the beloved Gaius, <crossref let="b" cid="c64001001.2"/>whom I love in truth.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v64001002"/>
    <begin-paragraph/>
    <verse num="2">Beloved, I pray that all may go well with you and that you may be in good health, as it goes well with your soul.</verse>
    <marker class="begin-verse" mid="v64001003"/>
    <verse num="3">For <crossref let="c" cid="c64001003.1"/>I rejoiced greatly when the brothers<note nid="n64001003.1"/> came and testified to your truth, as indeed you are walking in the truth.</verse>
    <marker class="begin-verse" mid="v64001004"/>
    <verse num="4">I have no greater joy than to hear that <crossref let="d" cid="c64001004.1"/>my children are walking in the truth.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v64001005"/>
    <heading>Support and Opposition</heading>
    <begin-paragraph/>
    <verse num="5">Beloved, it is a faithful thing you do in all your efforts for <crossref let="e" cid="c64001005.1"/>these brothers, <crossref let="f" cid="c64001005.2"/>strangers as they are,</verse>
    <marker class="begin-verse" mid="v64001006"/>
    <verse num="6">who testified to your love before the church. You will do well to send them on their journey in a manner <crossref let="g" cid="c64001006.1"/>worthy of God.</verse>
    <marker class="begin-verse" mid="v64001007"/>
    <verse num="7">For they have gone out for the sake of <crossref let="h" cid="c64001007.1"/>the name, <crossref let="i" cid="c64001007.2"/>accepting nothing from the Gentiles.</verse>
    <marker class="begin-verse" mid="v64001008"/>
    <verse num="8">Therefore we ought to support people like these, that we may be fellow workers for the truth.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v64001009"/>
    <begin-paragraph/>
    <verse num="9">I have written something to the church, but Diotrephes, who likes to put himself first, does not acknowledge our authority.</verse>
    <marker class="begin-verse" mid="v64001010"/>
    <verse num="10">So if I come, I will bring up what he is doing, talking wicked nonsense against us. And not content with that, he refuses to welcome the brothers, and also stops those who want to and puts them out of the church.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v64001011"/>
    <begin-paragraph/>
    <verse num="11">Beloved, <crossref let="j" cid="c64001011.1"/>do not imitate evil but imitate good. <crossref let="k" cid="c64001011.2"/>Whoever does good is from God; <crossref let="l" cid="c64001011.3"/>whoever does evil has not seen God.</verse>
    <marker class="begin-verse" mid="v64001012"/>
    <verse num="12">Demetrius <crossref let="m" cid="c64001012.1"/>has received a good testimony from everyone, and from the truth itself. We also add our testimony, and <crossref let="n" cid="c64001012.2"/>you know that our testimony is true.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v64001013"/>
    <heading>Final Greetings</heading>
    <begin-paragraph/>
    <verse num="13"><crossref let="o" cid="c64001013.1"/>I had much to write to you, but I would rather not write with pen and ink.</verse>
    <marker class="begin-verse" mid="v64001014"/>
    <verse num="14">I hope to see you soon, and we will talk face to face.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v64001015"/>
    <begin-paragraph/>
    <verse num="15">Peace be to you. The friends greet you. Greet the friends, <crossref let="p" cid="c64001015.1"/>each by name.</verse>
    <end-paragraph/>
  </chapter>
</book>
</crossway-bible>

=== blocher/dailyoffice2019/site/bible/esv/2 John.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE crossway-bible SYSTEM "schema/crossway.bibles.dtd">
<crossway-bible translation="English Standard Version" revision="2025-02-02" xmlns="http://www.crosswaybibles.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="schema/crossway.bibles.xsd">
<book title="2 John" num="63">
  <marker class="begin-verse" mid="v63001001"/>
  <chapter num="1">
    <heading>Greeting</heading>
    <begin-paragraph/>
    <verse num="1"><crossref let="a" cid="c63001001.1"/>The elder to the elect lady and her children, <crossref let="b" cid="c63001001.2"/>whom I love in truth, and not only I, but also all who <crossref let="c" cid="c63001001.3"/>know <crossref let="d" cid="c63001001.4"/>the truth,</verse>
    <marker class="begin-verse" mid="v63001002"/>
    <verse num="2"><crossref let="e" cid="c63001002.1"/>because of the truth that abides in us and will be with us forever:</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v63001003"/>
    <begin-paragraph/>
    <verse num="3"><crossref let="f" cid="c63001003.1"/>Grace, mercy, and peace will be with us, from God the Father and from Jesus Christ the Father&apos;s Son, in truth and love.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v63001004"/>
    <heading>Walking in Truth and Love</heading>
    <begin-paragraph/>
    <verse num="4"><crossref let="g" cid="c63001004.1"/>I rejoiced greatly to find some of your children walking in the truth, just as we were commanded by the Father.</verse>
    <marker class="begin-verse" mid="v63001005"/>
    <verse num="5">And now I ask you, dear lady&emdash;<crossref let="h" cid="c63001005.1"/>not as though I were writing you a new commandment, but the one we have had from the beginning&emdash;<crossref let="i" cid="c63001005.2"/>that we love one another.</verse>
    <marker class="begin-verse" mid="v63001006"/>
    <verse num="6">And <crossref let="j" cid="c63001006.1"/>this is love, that we walk according to his commandments; this is the commandment, just <crossref let="k" cid="c63001006.2"/>as you have heard from the beginning, so that you should walk in it.</verse>
    <marker class="begin-verse" mid="v63001007"/>
    <verse num="7">For <crossref let="l" cid="c63001007.1"/>many deceivers <crossref let="m" cid="c63001007.2"/>have gone out into the world, <crossref let="n" cid="c63001007.3"/>those who do not confess the coming of Jesus Christ in the flesh. Such a one is the deceiver and the antichrist.</verse>
    <marker class="begin-verse" mid="v63001008"/>
    <verse num="8">Watch yourselves, <crossref let="o" cid="c63001008.1"/>so that you may not lose what we<note nid="n63001008.1"/> have worked for, but <crossref let="p" cid="c63001008.2"/>may win a full reward.</verse>
    <marker class="begin-verse" mid="v63001009"/>
    <verse num="9">Everyone who goes on ahead and does not abide in the teaching of Christ, <crossref let="q" cid="c63001009.1"/>does not have God. Whoever abides in the teaching <crossref let="q" cid="c63001009.2"/>has both the Father and the Son.</verse>
    <marker class="begin-verse" mid="v63001010"/>
    <verse num="10">If anyone comes to you and does not bring this teaching, <crossref let="r" cid="c63001010.1"/>do not receive him into your house or give him any greeting,</verse>
    <marker class="begin-verse" mid="v63001011"/>
    <verse num="11">for whoever greets him <crossref let="s" cid="c63001011.1"/>takes part in his wicked works.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v63001012"/>
    <heading>Final Greetings</heading>
    <begin-paragraph/>
    <verse num="12"><crossref let="t" cid="c63001012.1"/>Though I have much to write to you, I would rather not use paper and ink. <crossref let="u" cid="c63001012.2"/>Instead I hope to come to you and talk face to face, <crossref let="v" cid="c63001012.3"/>so that our joy may be complete.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v63001013"/>
    <begin-paragraph/>
    <verse num="13">The children of your elect sister greet you.</verse>
    <end-paragraph/>
  </chapter>
</book>
</crossway-bible>
