=== blocher/dailyoffice2019/site/bible/esv/schema/crossway.bibles.dtd
<!ELEMENT crossway-bible (book)+>
<!ATTLIST crossway-bible  translation CDATA #REQUIRED
                          revision CDATA #REQUIRED
                          xmlns:xsi CDATA #IMPLIED
                          xmlns CDATA #IMPLIED
                          xsi:schemaLocation CDATA #IMPLIED>

<!ELEMENT book (chapter|heading|marker)+>
<!ATTLIST book  title CDATA #REQUIRED
                num CDATA #REQUIRED>

<!ELEMENT chapter (#PCDATA|begin-block-indent|begin-paragraph|end-block-indent|end-paragraph|heading|subheading|verse|marker|note)*>
<!ATTLIST chapter  num CDATA #REQUIRED>

<!ELEMENT subheading (#PCDATA|crossrefs|crossref|note|span|q)*>
<!ATTLIST subheading  class (psalm-acrostic-title|psalm-title|speaker|textual-note) #IMPLIED>

<!ELEMENT begin-block-indent EMPTY>
<!ELEMENT begin-paragraph    EMPTY>
<!ATTLIST begin-paragraph    class (same-paragraph|extra-space|line-group) #IMPLIED>
<!ELEMENT end-block-indent   EMPTY>
<!ELEMENT end-paragraph      EMPTY>

<!-- How far to indent -->
<!ELEMENT begin-line EMPTY>
<!ATTLIST begin-line class (indent|indent-2|declares|psalm-doxology) #IMPLIED>
<!-- class="br" indicates a line break -->
<!ELEMENT end-line   EMPTY>
<!ATTLIST end-line   class (br) #IMPLIED>

<!-- class="psalm-book" is only in the Psalms -->
<!ELEMENT heading (#PCDATA|span|note)*>
<!ATTLIST heading class (psalm-book) #IMPLIED>

<!ELEMENT verse  (#PCDATA|begin-paragraph|end-paragraph|begin-block-indent|end-block-indent|begin-line|end-line|span|note|crossrefs|crossref|woc|heading|subheading|selah|q|deutero)*>
<!ATTLIST verse   class (woc) #IMPLIED
                  num CDATA #REQUIRED
                  altnum CDATA #IMPLIED>

<!ELEMENT deutero (#PCDATA|begin-paragraph|end-paragraph|begin-block-indent|end-block-indent|begin-line|end-line|span|note|crossrefs|crossref|woc|heading|subheading|selah|q)*>

<!-- class="us-time" appears only in notes -->
<!ELEMENT span (#PCDATA)>
<!ATTLIST span  class (divine-name|us-time|small-caps) #IMPLIED>

<!ELEMENT selah (#PCDATA|note|crossrefs|crossref)*>

<!-- Words of Christ; never crosses a paragraph -->
<!ELEMENT woc (#PCDATA|span|note|begin-line|end-line|crossrefs|crossref|q)*>

<!-- contains two or more crossrefs that need to be separated by a comma
     (or a comma and space)-->
<!ELEMENT crossrefs (crossref)+>

<!ELEMENT crossref EMPTY>
<!ATTLIST crossref let CDATA #IMPLIED
                   cid ID #REQUIRED>

<!-- notes themselves contain (#PCDATA|a|i|verse-num|span)* -->
<!ELEMENT note EMPTY>
<!ATTLIST note nid CDATA #REQUIRED>

<!ELEMENT q EMPTY>
<!ATTLIST q class CDATA #REQUIRED
            qid CDATA #REQUIRED
            from CDATA #IMPLIED
            to CDATA #IMPLIED>

<!--
<marker> is designed to indicate the placement of
arbitrary data for various editions; the goal is to clutter the Bible XML files
as little as possible with a proliferation of non-Bible content;

mid="..." should use a unique alphabetic prefix that can be queried with XPath;
ideally, the rest of "mid" should be an 8-digit number indicating the verse where
it appears (or should be attached to; a book introduction would be part of the
first verse of the first chapter of the book

class="..." is optional and can be used to make it easier to determine the type
of marker; for example, a complete marker for an introduction to John in the
text-only edition might be:
	<marker class="intro" mid="it43001001"/>
In the cross-reference edition, it might be:
	<marker class="intro" mid="ic43001001"/>
Taken together, you would have the following fragment:
	<book title="John" num="43">
		<marker class="intro" mid="it43001001"/>
		<marker class="intro" mid="ic43001001"/>
		<chapter num="1">
			<heading>...etc...
-->
<!ELEMENT marker EMPTY>
<!ATTLIST marker class CDATA #IMPLIED
                 mid CDATA #REQUIRED>

<!-- link to preface for certain footnotes -->
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #IMPLIED>

<!-- italic text for certain footnotes -->
<!ELEMENT i (#PCDATA|span)*>

<!ELEMENT verse-num (#PCDATA)>

<!-- Entities -->
<!ENTITY ldblquot  "&#8220;">
<!ENTITY rdblquot  "&#8221;">
<!ENTITY lquot     "&#8216;">
<!ENTITY rquot     "&#8217;">
<!ENTITY emdash    "&#8212;">
<!ENTITY endash    "&#8211;">
<!ENTITY ellipsis  "&#160;.&#160;.&#160;.">
<!ENTITY ellipsis4 ".&#160;.&#160;.&#160;.">
<!ENTITY emacron   "&#275;">

=== blocher/dailyoffice2019/site/bible/esv/Philemon.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE crossway-bible SYSTEM "schema/crossway.bibles.dtd">
<crossway-bible translation="English Standard Version" revision="2025-02-02" xmlns="http://www.crosswaybibles.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="schema/crossway.bibles.xsd">
<book title="Philemon" num="57">
  <marker class="begin-verse" mid="v57001001"/>
  <chapter num="1">
    <heading>Greeting</heading>
    <begin-paragraph/>
    <verse num="1">Paul, <crossref let="a" cid="c57001001.1"/>a prisoner for Christ Jesus, and <crossref let="b" cid="c57001001.2"/>Timothy our brother,
      <end-paragraph/>
      <begin-paragraph/>To Philemon our beloved fellow worker
    </verse>
    <marker class="begin-verse" mid="v57001002"/>
    <verse num="2">and Apphia our sister and <crossref let="c" cid="c57001002.1"/>Archippus our <crossref let="d" cid="c57001002.2"/>fellow soldier, and <crossref let="e" cid="c57001002.3"/>the church in your house:</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v57001003"/>
    <begin-paragraph/>
    <verse num="3"><crossref let="f" cid="c57001003.1"/>Grace to you and peace from God our Father and the Lord Jesus Christ.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v57001004"/>
    <heading>Philemon&apos;s Love and Faith</heading>
    <begin-paragraph/>
    <verse num="4"><crossref let="g" cid="c57001004.1"/>I thank my God always when I remember you in my prayers,</verse>
    <marker class="begin-verse" mid="v57001005"/>
    <verse num="5">because I <crossref let="h" cid="c57001005.1"/>hear of your love and <crossref let="i" cid="c57001005.2"/>of the faith that you have toward the Lord Jesus and for all the saints,</verse>
    <marker class="begin-verse" mid="v57001006"/>
    <verse num="6">and I pray that the sharing of your faith may become effective for the full <crossref let="j" cid="c57001006.1"/>knowledge of every good thing that is in us for the sake of Christ.<note nid="n57001006.1"/></verse>
    <marker class="begin-verse" mid="v57001007"/>
    <verse num="7">For I have derived much joy and <crossref let="k" cid="c57001007.1"/>comfort from your love, my brother, because the hearts of the saints <crossref let="l" cid="c57001007.2"/>have been refreshed through you.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v57001008"/>
    <heading>Paul&apos;s Plea for Onesimus</heading>
    <begin-paragraph/>
    <verse num="8">Accordingly, <crossref let="m" cid="c57001008.1"/>though I am bold enough in Christ to command you to do <crossref let="n" cid="c57001008.2"/>what is required,</verse>
    <marker class="begin-verse" mid="v57001009"/>
    <verse num="9">yet for love&apos;s sake I prefer to appeal to you&emdash;I, Paul, an old man and now <crossref let="o" cid="c57001009.1"/>a prisoner also for Christ Jesus&emdash;</verse>
    <marker class="begin-verse" mid="v57001010"/>
    <verse num="10">I appeal to you for <crossref let="p" cid="c57001010.1"/>my child, <crossref let="q" cid="c57001010.2"/>Onesimus,<note nid="n57001010.1"/> <crossref let="r" cid="c57001010.3"/>whose father I became in my imprisonment.</verse>
    <marker class="begin-verse" mid="v57001011"/>
    <verse num="11">(Formerly he was useless to you, but now he is indeed useful to you and to me.)</verse>
    <marker class="begin-verse" mid="v57001012"/>
    <verse num="12">I am sending him back to you, sending my very heart.</verse>
    <marker class="begin-verse" mid="v57001013"/>
    <verse num="13">I would have been glad to keep him with me, in order that he might serve me <crossref let="s" cid="c57001013.1"/>on your behalf <crossref let="t" cid="c57001013.2"/>during my imprisonment for the gospel,</verse>
    <marker class="begin-verse" mid="v57001014"/>
    <verse num="14">but I preferred to do nothing without your consent in order that your goodness might not be <crossref let="u" cid="c57001014.1"/>by compulsion but of your own accord.</verse>
    <marker class="begin-verse" mid="v57001015"/>
    <verse num="15">For this perhaps is why <crossref let="v" cid="c57001015.1"/>he was parted from you for a while, that you might have him back forever,</verse>
    <marker class="begin-verse" mid="v57001016"/>
    <verse num="16"><crossref let="w" cid="c57001016.1"/>no longer as a bondservant<note nid="n57001016.1"/> but more than a bondservant, as <crossref let="x" cid="c57001016.2"/>a beloved brother&emdash;especially to me, but how much more to you, <crossref let="y" cid="c57001016.3"/>both in the flesh and in the Lord.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v57001017"/>
    <begin-paragraph/>
    <verse num="17">So if you consider me <crossref let="z" cid="c57001017.1"/>your partner, receive him as you would receive me.</verse>
    <marker class="begin-verse" mid="v57001018"/>
    <verse num="18">If he has wronged you at all, or owes you anything, charge that to my account.</verse>
    <marker class="begin-verse" mid="v57001019"/>
    <verse num="19"><crossref let="a" cid="c57001019.1"/>I, Paul, write this with my own hand: I will repay it&emdash;to say nothing of your owing me even your own self.</verse>
    <marker class="begin-verse" mid="v57001020"/>
    <verse num="20">Yes, brother, I want some benefit from you in the Lord. <crossref let="b" cid="c57001020.1"/>Refresh my heart in Christ.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v57001021"/>
    <begin-paragraph/>
    <verse num="21"><crossref let="c" cid="c57001021.1"/>Confident of your obedience, I write to you, knowing that you will do even more than I say.</verse>
    <marker class="begin-verse" mid="v57001022"/>
    <verse num="22">At the same time, prepare a guest room for me, for <crossref let="d" cid="c57001022.1"/>I am hoping that <crossref let="e" cid="c57001022.2"/>through your prayers <crossref let="f" cid="c57001022.3"/>I will be graciously given to you.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v57001023"/>
    <heading>Final Greetings</heading>
    <begin-paragraph/>
    <verse num="23"><crossref let="g" cid="c57001023.1"/>Epaphras, my <crossref let="h" cid="c57001023.2"/>fellow prisoner in Christ Jesus, sends greetings to you,</verse>
    <marker class="begin-verse" mid="v57001024"/>
    <verse num="24">and so do <crossref let="i" cid="c57001024.1"/>Mark, <crossref let="i" cid="c57001024.2"/>Aristarchus, <crossref let="j" cid="c57001024.3"/>Demas, and <crossref let="j" cid="c57001024.4"/>Luke, my fellow workers.</verse>
    <end-paragraph/>
    <marker class="begin-verse" mid="v57001025"/>
    <begin-paragraph/>
    <verse num="25"><crossref let="k" cid="c57001025.1"/>The grace of the Lord Jesus Christ be with your spirit.</verse>
    <end-paragraph/>
  </chapter>
</book>
</crossway-bible>

=== blocher/dailyoffice2019/site/bible/esv/83.Prayer of Manasseh.xml
<?xml version='1.0' encoding='utf-8' standalone='yes'?>
<!DOCTYPE crossway-bible SYSTEM "schema/crossway.bibles.dtd">
<crossway-bible xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" translation="English Standard Version" revision="2018-3-26" xmlns="http://www.crosswaybibles.org" xsi:schemaLocation="schema/crossway.bibles.xsd">
  <book title="Prayer of Manasseh" num="83">
    <marker class="begin-verse" mid="v83001001"/>
    <chapter num="1">
      <heading>Ascription of Praise</heading>
      <begin-block-indent/>
      <begin-paragraph class="line-group"/>
      <verse num="1"><begin-line/>O Lord Almighty,<end-line class="br"/><begin-line class="indent"/>the God of our fathers,<end-line class="br"/><begin-line/>of Abraham and Isaac and Jacob,<end-line class="br"/><begin-line class="indent"/>and of their righteous descendants;<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001002"/>
      <verse num="2"><begin-line/>you who made heaven and earth<end-line class="br"/><begin-line class="indent"/>with all their order;<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001003"/>
      <verse num="3"><begin-line/>who shackled the sea by your word of command,<end-line class="br"/><begin-line class="indent"/>who closed up the deep<end-line class="br"/><begin-line class="indent"/>and sealed it with your terrible and glorious name;<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001004"/>
      <verse num="4"><begin-line/>at whom all things shudder<end-line class="br"/><begin-line class="indent"/>and tremble before your power,<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001005"/>
      <verse num="5"><begin-line/>for your glorious splendor is unendurable,<end-line class="br"/><begin-line class="indent"/>and the wrath of your threat to sinners is overpowering;<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001006"/>
      <verse num="6"><begin-line/>yet immeasurable and unsearchable is your promised mercy,<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001007"/>
      <verse num="7"><begin-line class="indent"/>for you are the Lord Most High,<end-line class="br"/><begin-line/>of great compassion, patient, and very merciful,<end-line class="br"/><begin-line class="indent"/>repenting over the evils of human beings.<note nid="n83001007.1"/><end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001008"/>
      <verse num="8"><begin-line/>Therefore you, O Lord, God of the righteous,<end-line class="br"/><begin-line class="indent"/>did not appoint repentance for the righteous,<end-line class="br"/><begin-line/>for Abraham and Isaac and Jacob, who did not sin against you,<end-line class="br"/><begin-line class="indent"/>but you have appointed repentance for me, the sinner.<end-line/></verse>
      <end-paragraph/>
      <end-block-indent/>
      <marker class="begin-verse" mid="v83001009"/>
      <heading>Confession of Sins</heading>
      <begin-block-indent/>
      <begin-paragraph class="line-group"/>
      <verse num="9"><begin-line/>For the sins I committed are more in number than the sand of the sea;<end-line class="br"/><begin-line class="indent"/>my transgressions are multiplied, O Lord, they are multiplied!<end-line class="br"/><begin-line/>I am unworthy to look up and see the height of heaven<end-line class="br"/><begin-line class="indent"/>because of the multitude of my iniquities.<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001010"/>
      <verse num="10"><begin-line/>I am weighted down with many an iron fetter,<end-line class="br"/><begin-line class="indent"/>so that I am rejected because of my sins,<end-line class="br"/><begin-line class="indent"/>and I have no relief;<end-line class="br"/><begin-line/>for I provoked your wrath<end-line class="br"/><begin-line class="indent"/>and did what is evil in your sight,<end-line class="br"/><begin-line class="indent"/>setting up abominations and multiplying offenses.<end-line/></verse>
      <end-paragraph/>
      <end-block-indent/>
      <marker class="begin-verse" mid="v83001011"/>
      <heading>Supplication for Pardon</heading>
      <begin-block-indent/>
      <begin-paragraph class="line-group"/>
      <verse num="11"><begin-line/>And now I bend the knee of my heart,<end-line class="br"/><begin-line class="indent"/>imploring you for your kindness.<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001012"/>
      <verse num="12"><begin-line/>I have sinned, O Lord, I have sinned,<end-line class="br"/><begin-line class="indent"/>and I know my transgressions.<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001013"/>
      <verse num="13"><begin-line/>I earnestly implore you,<end-line class="br"/><begin-line class="indent"/>forgive me, O Lord, forgive me!<end-line class="br"/><begin-line class="indent"/>Do not destroy me with my transgressions!<end-line class="br"/><begin-line/>Do not be angry with me forever or lay up evil for me;<end-line class="br"/><begin-line class="indent"/>do not condemn me to the depths of the earth.<end-line class="br"/><begin-line/>For you, O Lord, are the God of those who repent,<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001014"/>
      <verse num="14"><begin-line class="indent"/>and in me you will show forth your goodness;<end-line class="br"/><begin-line/>for, unworthy as I am, you will save me in your great mercy,<end-line class="br"/></verse>
      <marker class="begin-verse" mid="v83001015"/>
      <verse num="15"><begin-line class="indent"/>and I will praise you continually all the days of my life.<end-line class="br"/><begin-line/>For all the might of heaven sings your praise,<end-line class="br"/><begin-line class="indent"/>and yours is the glory forever. Amen.<end-line/></verse>
      <end-paragraph/>
      <end-block-indent/>
    </chapter>
  </book>
</crossway-bible>
